version: "3.8"
services:
  zookeeper:
    image: zookeeper:latest
    restart: always
    ports:
      - "2181:2181"
    volumes:
      - ./kafka/zookeeper/data:/data
      - ./kafka/zookeeper/datalog:/datalog

  kafka:
    image: wurstmeister/kafka:latest
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_CREATE_TOPICS: "message:1:1"
      KAFKA_ADVERTISED_HOST_NAME: "192.168.99.100"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    depends_on:
      - zookeeper
