CREATE DATABASE IF NOT EXISTS `tokoin`;
CREATE DATABASE IF NOT EXISTS `tokoin_bo`;
CREATE DATABASE IF NOT EXISTS `tokoin_pos_local`;
CREATE DATABASE IF NOT EXISTS `bds`;
CREATE DATABASE IF NOT EXISTS `bds_bo`;